# Generated by Django 3.0 on 2020-05-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200512_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
