# Generated by Django 3.1 on 2020-08-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='diseaseinfo',
        ),
    ]
